### ISSUE TITLE
Warnings with later clojure versions

### ISSUE THREAD

**Issue by sammedino** [liwp/ring-congestion#5]
Thanks for writing this library.

We're on clojure 1.10 and we're seeing these warnings:

```
WARNING: pos-int? already refers to: #'clojure.core/pos-int? in namespace: taoensso.encore, being replaced by: #'taoensso.encore/pos-int?
WARNING: bytes? already refers to: #'clojure.core/bytes? in namespace: taoensso.encore, being replaced by: #'taoensso.encore/bytes?
```

They will be fixed by upgrading the encore library. 
Would you open to a PR for this fix?

**Comment by liwp** [comment]
Thanks for the report. I'll try to have a look at this this coming weekend.

**Comment by liwp** [comment]
@sammedino I've upgraded the dependencies including `clojure` to `v1.10.0` and pushed a `0.13.0` release to clojars. Looks like `v1.11.x` will introduce more name conflicts with `encore` etc, so I'll have to deal with that in the future.

Please give a it whirl and let me know if I broke something, and thanks for reporting the issue!

**Comment by sam-d-2** [comment]
@liwp Great, thanks! 
I will get it updated and let you know if I spot any issues.
